INSERT INTO `profile` VALUES (1, 'Test user', '571xRkrdqdnxfM7cenA8ltsOATg6UtQF3BRxDxiqinw', 'Favourite colour?', 'Orange', NULL);

INSERT INTO `langset` VALUES (0, 'Colours', 1, 0, 1);
INSERT INTO `langset` VALUES (1, 'Days of the Week', 1, 0, 1);
INSERT INTO `langset` VALUES (2, 'Numbers 1-10', 1, 0, 1);
INSERT INTO `langset` VALUES (3, 'Alphabet', 2, 0, 1);
INSERT INTO `langset` VALUES (4, 'Food', 2, 0, 1);
INSERT INTO `langset` VALUES (5, 'Months', 2, 0, 1);
INSERT INTO `langset` VALUES (6, 'Numbers 11-50', 2, 0, 1);
INSERT INTO `langset` VALUES (7, 'Clothing', 2, 0, 1);
INSERT INTO `langset` VALUES (8, 'Verbs', 3, 0, 1);
INSERT INTO `langset` VALUES (9, 'Male/Female', 3, 0, 1);

INSERT INTO `langentity` VALUES(0, 0, 0, "one", "uno", 0, 0);
INSERT INTO `langentity` VALUES(1, 0, 0, "two", "dos", 0, 0);
INSERT INTO `langentity` VALUES(2, 0, 0, "three", "tres", 0, 0);
INSERT INTO `langentity` VALUES(3, 0, 0, "four", "cuatro", 0, 0);
INSERT INTO `langentity` VALUES(4, 0, 0, "five", "cinco", 0, 0);
INSERT INTO `langentity` VALUES(5, 0, 0, "six", "seis", 0, 0);
INSERT INTO `langentity` VALUES(6, 0, 0, "seven", "siete", 0, 0);
INSERT INTO `langentity` VALUES(7, 0, 0, "eight", "ocho", 0, 0);
INSERT INTO `langentity` VALUES(8, 0, 0, "nine", "nueve", 0, 0);
INSERT INTO `langentity` VALUES(9, 0, 0, "ten", "diez", 0, 0);
INSERT INTO `langentity` VALUES(10, 0, 0, "Monday", "Lunes", 0, 0);
INSERT INTO `langentity` VALUES(11, 0, 0, "Tuesday", "Martes", 0, 0);
INSERT INTO `langentity` VALUES(12, 0, 0, "Wednesday", "Miercoles", 0, 0);
INSERT INTO `langentity` VALUES(13, 0, 0, "Thursday", "Jueves", 0, 0);
INSERT INTO `langentity` VALUES(14, 0, 0, "Friday", "Viernes", 0, 0);
INSERT INTO `langentity` VALUES(15, 0, 0, "Saturday", "Sabado", 0, 0);
INSERT INTO `langentity` VALUES(16, 0, 0, "Sunday", "Domingo", 0, 0);
INSERT INTO `langentity` VALUES(17, 0, 0, "Red", "Rojo", 0, 0);
INSERT INTO `langentity` VALUES(18, 0, 0, "Orange", "Naranja", 0, 0);
INSERT INTO `langentity` VALUES(19, 0, 0, "Yellow", "Amarillo", 0, 0);
INSERT INTO `langentity` VALUES(20, 0, 0, "Green", "Verde", 0, 0);
INSERT INTO `langentity` VALUES(21, 0, 0, "Blue", "Azul", 0, 0);
INSERT INTO `langentity` VALUES(22, 0, 0, "Purple", "Morado", 0, 0);
INSERT INTO `langentity` VALUES(23, 0, 0, "Pink ", "Rosa", 0, 0);
INSERT INTO `langentity` VALUES(24, 0, 0, "White", "Blanco", 0, 0);
INSERT INTO `langentity` VALUES(25, 0, 0, "Black", "Negro", 0, 0);
INSERT INTO `langentity` VALUES(26, 0, 0, "Brown", "Marron", 0, 0);
INSERT INTO `langentity` VALUES(27, 0, 0, "A", "a", 0, 0);
INSERT INTO `langentity` VALUES(28, 0, 0, "B", "be", 0, 0);
INSERT INTO `langentity` VALUES(29, 0, 0, "C", "ce", 0, 0);
INSERT INTO `langentity` VALUES(30, 0, 0, "Ch", "che", 0, 0);
INSERT INTO `langentity` VALUES(31, 0, 0, "D", "de", 0, 0);
INSERT INTO `langentity` VALUES(32, 0, 0, "E", "e", 0, 0);
INSERT INTO `langentity` VALUES(33, 0, 0, "F", "efe", 0, 0);
INSERT INTO `langentity` VALUES(34, 0, 0, "G", "ge", 0, 0);
INSERT INTO `langentity` VALUES(35, 0, 0, "H", "hache", 0, 0);
INSERT INTO `langentity` VALUES(36, 0, 0, "I", "i", 0, 0);
INSERT INTO `langentity` VALUES(37, 0, 0, "J", "jota", 0, 0);
INSERT INTO `langentity` VALUES(38, 0, 0, "K", "ca", 0, 0);
INSERT INTO `langentity` VALUES(39, 0, 0, "L", "ele", 0, 0);
INSERT INTO `langentity` VALUES(40, 0, 0, "LL", "elle", 0, 0);
INSERT INTO `langentity` VALUES(41, 0, 0, "M", "eme", 0, 0);
INSERT INTO `langentity` VALUES(42, 0, 0, "N", "ene", 0, 0);
INSERT INTO `langentity` VALUES(43, 0, 0, "ñ", "EñE", 0, 0);
INSERT INTO `langentity` VALUES(44, 0, 0, "O", "o", 0, 0);
INSERT INTO `langentity` VALUES(45, 0, 0, "P", "pe", 0, 0);
INSERT INTO `langentity` VALUES(46, 0, 0, "Q", "cu", 0, 0);
INSERT INTO `langentity` VALUES(47, 0, 0, "R", "ere", 0, 0);
INSERT INTO `langentity` VALUES(48, 0, 0, "RR", "erre", 0, 0);
INSERT INTO `langentity` VALUES(49, 0, 0, "S", "ese", 0, 0);
INSERT INTO `langentity` VALUES(50, 0, 0, "T", "te", 0, 0);
INSERT INTO `langentity` VALUES(51, 0, 0, "U", "u", 0, 0);
INSERT INTO `langentity` VALUES(52, 0, 0, "V", "ve", 0, 0);
INSERT INTO `langentity` VALUES(53, 0, 0, "W", "doble ve", 0, 0);
INSERT INTO `langentity` VALUES(54, 0, 0, "X", "equis", 0, 0);
INSERT INTO `langentity` VALUES(55, 0, 0, "Y", "i griega", 0, 0);
INSERT INTO `langentity` VALUES(56, 0, 0, "Z", "zeta", 0, 0);
INSERT INTO `langentity` VALUES(57, 0, 0, "Bread", "-Pan", 0, 0);
INSERT INTO `langentity` VALUES(58, 0, 0, "Milk", "Leche", 0, 0);
INSERT INTO `langentity` VALUES(59, 0, 0, "Potatoes", "Patatas", 0, 0);
INSERT INTO `langentity` VALUES(60, 0, 0, "Crisps", "Patatas fritas", 0, 0);
INSERT INTO `langentity` VALUES(61, 0, 0, "Juice", "Zumo", 0, 0);
INSERT INTO `langentity` VALUES(62, 0, 0, "Pasta", "Pasta", 0, 0);
INSERT INTO `langentity` VALUES(63, 0, 0, "Pizza", "Pizza", 0, 0);
INSERT INTO `langentity` VALUES(64, 0, 0, "Burgers", "Hamburguesas", 0, 0);
INSERT INTO `langentity` VALUES(65, 0, 0, "Chicken", "Pollo", 0, 0);
INSERT INTO `langentity` VALUES(66, 0, 0, "Meat", "Carne", 0, 0);
INSERT INTO `langentity` VALUES(67, 0, 0, "Fish", "Pescado", 0, 0);
INSERT INTO `langentity` VALUES(68, 0, 0, "Fruit", "Fruta", 0, 0);
INSERT INTO `langentity` VALUES(69, 0, 0, "Cereals", "Cereales", 0, 0);
INSERT INTO `langentity` VALUES(70, 0, 0, "Olives", "Aceitunas", 0, 0);
INSERT INTO `langentity` VALUES(71, 0, 0, "Spanish omellete", "Tortilla española", 0, 0);
INSERT INTO `langentity` VALUES(72, 0, 0, "Toast", "Tostada", 0, 0);
INSERT INTO `langentity` VALUES(73, 0, 0, "Eggs", "Huevos", 0, 0);
INSERT INTO `langentity` VALUES(74, 0, 0, "Cheese", "Queso", 0, 0);
INSERT INTO `langentity` VALUES(75, 0, 0, "Vegetables", "Verduras", 0, 0);
INSERT INTO `langentity` VALUES(76, 0, 0, "Ham", "Jamon", 0, 0);
INSERT INTO `langentity` VALUES(77, 0, 0, "Sauce", "Salsa", 0, 0);
INSERT INTO `langentity` VALUES(78, 0, 0, "Coffee", "Cafe", 0, 0);
INSERT INTO `langentity` VALUES(79, 0, 0, "January", "Enero", 0, 0);
INSERT INTO `langentity` VALUES(80, 0, 0, "February", "Febrero", 0, 0);
INSERT INTO `langentity` VALUES(81, 0, 0, "March", "Marzo", 0, 0);
INSERT INTO `langentity` VALUES(82, 0, 0, "April", "Abril", 0, 0);
INSERT INTO `langentity` VALUES(83, 0, 0, "May", "Mayo", 0, 0);
INSERT INTO `langentity` VALUES(84, 0, 0, "June", "Junio", 0, 0);
INSERT INTO `langentity` VALUES(85, 0, 0, "July", "Julio", 0, 0);
INSERT INTO `langentity` VALUES(86, 0, 0, "August", "Agosto", 0, 0);
INSERT INTO `langentity` VALUES(87, 0, 0, "September", "Septiembre", 0, 0);
INSERT INTO `langentity` VALUES(88, 0, 0, "October", "Octubre", 0, 0);
INSERT INTO `langentity` VALUES(89, 0, 0, "November", "Noviembre", 0, 0);
INSERT INTO `langentity` VALUES(90, 0, 0, "December", "Diciembre", 0, 0);
INSERT INTO `langentity` VALUES(91, 0, 0, "11", "once", 0, 0);
INSERT INTO `langentity` VALUES(92, 0, 0, "12", "doce", 0, 0);
INSERT INTO `langentity` VALUES(93, 0, 0, "13", "trece", 0, 0);
INSERT INTO `langentity` VALUES(94, 0, 0, "14", "catorce", 0, 0);
INSERT INTO `langentity` VALUES(95, 0, 0, "15", "quince", 0, 0);
INSERT INTO `langentity` VALUES(96, 0, 0, "16", "dieciséis", 0, 0);
INSERT INTO `langentity` VALUES(97, 0, 0, "17", "diecisiete", 0, 0);
INSERT INTO `langentity` VALUES(98, 0, 0, "18", "dieciocho", 0, 0);
INSERT INTO `langentity` VALUES(99, 0, 0, "19", "diecinueve", 0, 0);
INSERT INTO `langentity` VALUES(100, 0, 0, "20", "veinte", 0, 0);
INSERT INTO `langentity` VALUES(101, 0, 0, "21", "veintiuno", 0, 0);
INSERT INTO `langentity` VALUES(102, 0, 0, "22", "veintidós", 0, 0);
INSERT INTO `langentity` VALUES(103, 0, 0, "23", "veintitrés", 0, 0);
INSERT INTO `langentity` VALUES(104, 0, 0, "24", "veinticuatro", 0, 0);
INSERT INTO `langentity` VALUES(105, 0, 0, "25", "veinticinco", 0, 0);
INSERT INTO `langentity` VALUES(106, 0, 0, "26", "veintiséis", 0, 0);
INSERT INTO `langentity` VALUES(107, 0, 0, "27", "veintisiete", 0, 0);
INSERT INTO `langentity` VALUES(108, 0, 0, "28", "veintiocho", 0, 0);
INSERT INTO `langentity` VALUES(109, 0, 0, "29", "veintinueve", 0, 0);
INSERT INTO `langentity` VALUES(110, 0, 0, "30", "treinta", 0, 0);
INSERT INTO `langentity` VALUES(111, 0, 0, "31", "treinta y uno", 0, 0);
INSERT INTO `langentity` VALUES(112, 0, 0, "32", "treinta y dos", 0, 0);
INSERT INTO `langentity` VALUES(113, 0, 0, "33", "treinta y tres", 0, 0);
INSERT INTO `langentity` VALUES(114, 0, 0, "34", "treinta y cuatro", 0, 0);
INSERT INTO `langentity` VALUES(115, 0, 0, "35", "treinta y cinco", 0, 0);
INSERT INTO `langentity` VALUES(116, 0, 0, "36", "treinta y seis", 0, 0);
INSERT INTO `langentity` VALUES(117, 0, 0, "37", "treinta y siete", 0, 0);
INSERT INTO `langentity` VALUES(118, 0, 0, "38", "treinta y ocho", 0, 0);
INSERT INTO `langentity` VALUES(119, 0, 0, "39", "treinta y nueve", 0, 0);
INSERT INTO `langentity` VALUES(120, 0, 0, "40", "cuarenta", 0, 0);
INSERT INTO `langentity` VALUES(121, 0, 0, "41", "cuarenta y uno", 0, 0);
INSERT INTO `langentity` VALUES(122, 0, 0, "42", "cuarenta y dos", 0, 0);
INSERT INTO `langentity` VALUES(123, 0, 0, "43", "cuarenta y tres", 0, 0);
INSERT INTO `langentity` VALUES(124, 0, 0, "44", "cuarenta y cuatro", 0, 0);
INSERT INTO `langentity` VALUES(125, 0, 0, "45", "cuarenta y cinco", 0, 0);
INSERT INTO `langentity` VALUES(126, 0, 0, "46", "cuarenta y seis", 0, 0);
INSERT INTO `langentity` VALUES(127, 0, 0, "47", "cuarenta y siete", 0, 0);
INSERT INTO `langentity` VALUES(128, 0, 0, "48", "cuarenta y ocho", 0, 0);
INSERT INTO `langentity` VALUES(129, 0, 0, "49", "cuarenta y nueve", 0, 0);
INSERT INTO `langentity` VALUES(130, 0, 0, "50", "cincuenta", 0, 0);
INSERT INTO `langentity` VALUES(131, 0, 0, "Shoes", "unos Zapatos", 0, 0);
INSERT INTO `langentity` VALUES(132, 0, 0, "Trainers", "unas Deportivas", 0, 0);
INSERT INTO `langentity` VALUES(133, 0, 0, "Socks", "unos Calcetines", 0, 0);
INSERT INTO `langentity` VALUES(134, 0, 0, "Trousers", "unos Pantalones", 0, 0);
INSERT INTO `langentity` VALUES(135, 0, 0, "Skirt", "una Falda", 0, 0);
INSERT INTO `langentity` VALUES(136, 0, 0, "Short Skirt", "una Mini falda", 0, 0);
INSERT INTO `langentity` VALUES(137, 0, 0, "Shorts", "unos Shorts", 0, 0);
INSERT INTO `langentity` VALUES(138, 0, 0, "Hoodie", "una Sudadera", 0, 0);
INSERT INTO `langentity` VALUES(139, 0, 0, "Shirt", "una Camisa", 0, 0);
INSERT INTO `langentity` VALUES(140, 0, 0, "T-shirt", "una Camiseta", 0, 0);
INSERT INTO `langentity` VALUES(141, 0, 0, "Polo", "un Polo", 0, 0);
INSERT INTO `langentity` VALUES(142, 0, 0, "Jumper", "un Jersey", 0, 0);
INSERT INTO `langentity` VALUES(143, 0, 0, "Jacket", "una Chaqueta", 0, 0);
INSERT INTO `langentity` VALUES(144, 0, 0, "Coat", "un Abrigo", 0, 0);
INSERT INTO `langentity` VALUES(145, 0, 0, "Hat", "un Sombrero", 0, 0);
INSERT INTO `langentity` VALUES(146, 0, 0, "Cap", "una Gorra", 0, 0);
INSERT INTO `langentity` VALUES(147, 0, 0, "Boxers", "unos Calzoncillos", 0, 0);
INSERT INTO `langentity` VALUES(148, 0, 0, "Knickers", "unas Bragas", 0, 0);
INSERT INTO `langentity` VALUES(149, 0, 0, "Gloves", "unos Guantes", 0, 0);
INSERT INTO `langentity` VALUES(150, 0, 0, "Scarf", "una Bufanda", 0, 0);
INSERT INTO `langentity` VALUES(151, 0, 0, "Belt", "un Cinturon", 0, 0);
INSERT INTO `langentity` VALUES(152, 0, 0, "Flipflops", "unas Chanclas", 0, 0);
INSERT INTO `langentity` VALUES(153, 0, 0, "Swimwear", "un Bañador", 0, 0);
INSERT INTO `langentity` VALUES(154, 0, 0, "Bikini", "un Bikini", 0, 0);
INSERT INTO `langentity` VALUES(155, 1, 0, "My name is...", "Mi nombre es", 0, 0);
INSERT INTO `langentity` VALUES(156, 1, 0, "What is your name?", "¿Cual es tu nombre?", 0, 0);
INSERT INTO `langentity` VALUES(157, 1, 0, "I am...years old", "Tengo...anos", 0, 0);
INSERT INTO `langentity` VALUES(158, 1, 0, "I live in...", "Viro en...", 0, 0);
INSERT INTO `langentity` VALUES(159, 1, 0, "Where do you live?", "¿Donde vires tu?", 0, 0);
INSERT INTO `langentity` VALUES(160, 1, 0, "My birthday is on...", "Mi cumpleanos es el...", 0, 0);
INSERT INTO `langentity` VALUES(161, 1, 0, "My favourite subject is...", "Mi asignutura favorita es/son….", 0, 0);
INSERT INTO `langentity` VALUES(162, 1, 0, "I have...brothers/sisters", "Tengo…hermanos/hermanas", 0, 0);
INSERT INTO `langentity` VALUES(163, 1, 0, "I am...tall", "Yo Mido…", 0, 0);
INSERT INTO `langentity` VALUES(164, 1, 0, "I weigh", "Yo Peso…", 0, 0);
INSERT INTO `langentity` VALUES(165, 1, 0, "I study...", "Yo estudio…", 0, 0);
INSERT INTO `langentity` VALUES(166, 1, 0, "I was born in...", "Naci en…", 0, 0);
INSERT INTO `langentity` VALUES(167, 1, 0, "My siblings name is...", "El nombre de mi hermano/hermana es…", 0, 0);
INSERT INTO `langentity` VALUES(168, 1, 0, "They are...years old", "Tienen… anos", 0, 0);
INSERT INTO `langentity` VALUES(169, 1, 0, "My favourite hobby is...", "Mi hobby favorito es..", 0, 0);
INSERT INTO `langentity` VALUES(170, 1, 0, "I wish I could...", "Me gustaria poder..", 0, 0);
INSERT INTO `langentity` VALUES(171, 1, 0, "I can't...", "No puedo...", 0, 0);
INSERT INTO `langentity` VALUES(172, 1, 0, "In my house I have...", "En mi casa tengo..", 0, 0);
INSERT INTO `langentity` VALUES(173, 1, 0, "Today I used/had a...", "Hoy he usado", 0, 0);
INSERT INTO `langentity` VALUES(174, 1, 0, "My favourite food is...", "Mi comidu favorita es.. ", 0, 0);
INSERT INTO `langentity` VALUES(175, 1, 0, "My favourite colour is...", "Mi color favorito..", 0, 0);
INSERT INTO `langentity` VALUES(176, 1, 0, "I don't like the colour...", "No me gusta el color..", 0, 0);
INSERT INTO `langentity` VALUES(177, 1, 0, "I am wearing...", "Llevo puesto aglo..", 0, 0);
INSERT INTO `langentity` VALUES(178, 1, 0, "What time is it?", "Que hora es...?", 0, 0);
INSERT INTO `langentity` VALUES(179, 1, 0, "It is...", "Son las...", 0, 0);
INSERT INTO `langentity` VALUES(180, 1, 0, "It is quarter past...", "Son las …. y cuarto", 0, 0);
INSERT INTO `langentity` VALUES(181, 1, 0, "It is half past...", "Son las …. y media", 0, 0);
INSERT INTO `langentity` VALUES(182, 1, 0, "It is quarter to...", "Son las … menos cuarto", 0, 0);

INSERT INTO `entity_set` VALUES(0, 2);
INSERT INTO `entity_set` VALUES(1, 2);
INSERT INTO `entity_set` VALUES(2, 2);
INSERT INTO `entity_set` VALUES(3, 2);
INSERT INTO `entity_set` VALUES(4, 2);
INSERT INTO `entity_set` VALUES(5, 2);
INSERT INTO `entity_set` VALUES(6, 2);
INSERT INTO `entity_set` VALUES(7, 2);
INSERT INTO `entity_set` VALUES(8, 2);
INSERT INTO `entity_set` VALUES(9, 2);
INSERT INTO `entity_set` VALUES(10, 1);
INSERT INTO `entity_set` VALUES(11, 1);
INSERT INTO `entity_set` VALUES(12, 1);
INSERT INTO `entity_set` VALUES(13, 1);
INSERT INTO `entity_set` VALUES(14, 1);
INSERT INTO `entity_set` VALUES(15, 1);
INSERT INTO `entity_set` VALUES(16, 1);
INSERT INTO `entity_set` VALUES(17, 0);
INSERT INTO `entity_set` VALUES(18, 0);
INSERT INTO `entity_set` VALUES(19, 0);
INSERT INTO `entity_set` VALUES(20, 0);
INSERT INTO `entity_set` VALUES(21, 0);
INSERT INTO `entity_set` VALUES(22, 0);
INSERT INTO `entity_set` VALUES(23, 0);
INSERT INTO `entity_set` VALUES(24, 0);
INSERT INTO `entity_set` VALUES(25, 0);
INSERT INTO `entity_set` VALUES(26, 0);
INSERT INTO `entity_set` VALUES(27, 3);
INSERT INTO `entity_set` VALUES(28, 3);
INSERT INTO `entity_set` VALUES(29, 3);
INSERT INTO `entity_set` VALUES(30, 3);
INSERT INTO `entity_set` VALUES(31, 3);
INSERT INTO `entity_set` VALUES(32, 3);
INSERT INTO `entity_set` VALUES(33, 3);
INSERT INTO `entity_set` VALUES(34, 3);
INSERT INTO `entity_set` VALUES(35, 3);
INSERT INTO `entity_set` VALUES(36, 3);
INSERT INTO `entity_set` VALUES(37, 3);
INSERT INTO `entity_set` VALUES(38, 3);
INSERT INTO `entity_set` VALUES(39, 3);
INSERT INTO `entity_set` VALUES(40, 3);
INSERT INTO `entity_set` VALUES(41, 3);
INSERT INTO `entity_set` VALUES(42, 3);
INSERT INTO `entity_set` VALUES(43, 3);
INSERT INTO `entity_set` VALUES(44, 3);
INSERT INTO `entity_set` VALUES(45, 3);
INSERT INTO `entity_set` VALUES(46, 3);
INSERT INTO `entity_set` VALUES(47, 3);
INSERT INTO `entity_set` VALUES(48, 3);
INSERT INTO `entity_set` VALUES(49, 3);
INSERT INTO `entity_set` VALUES(50, 3);
INSERT INTO `entity_set` VALUES(51, 3);
INSERT INTO `entity_set` VALUES(52, 3);
INSERT INTO `entity_set` VALUES(53, 3);
INSERT INTO `entity_set` VALUES(54, 3);
INSERT INTO `entity_set` VALUES(55, 3);
INSERT INTO `entity_set` VALUES(56, 3);
INSERT INTO `entity_set` VALUES(57, 4);
INSERT INTO `entity_set` VALUES(58, 4);
INSERT INTO `entity_set` VALUES(59, 4);
INSERT INTO `entity_set` VALUES(60, 4);
INSERT INTO `entity_set` VALUES(61, 4);
INSERT INTO `entity_set` VALUES(62, 4);
INSERT INTO `entity_set` VALUES(63, 4);
INSERT INTO `entity_set` VALUES(64, 4);
INSERT INTO `entity_set` VALUES(65, 4);
INSERT INTO `entity_set` VALUES(66, 4);
INSERT INTO `entity_set` VALUES(67, 4);
INSERT INTO `entity_set` VALUES(68, 4);
INSERT INTO `entity_set` VALUES(69, 4);
INSERT INTO `entity_set` VALUES(70, 4);
INSERT INTO `entity_set` VALUES(71, 4);
INSERT INTO `entity_set` VALUES(72, 4);
INSERT INTO `entity_set` VALUES(73, 4);
INSERT INTO `entity_set` VALUES(74, 4);
INSERT INTO `entity_set` VALUES(75, 4);
INSERT INTO `entity_set` VALUES(76, 4);
INSERT INTO `entity_set` VALUES(77, 4);
INSERT INTO `entity_set` VALUES(78, 4);
INSERT INTO `entity_set` VALUES(79, 5);
INSERT INTO `entity_set` VALUES(80, 5);
INSERT INTO `entity_set` VALUES(81, 5);
INSERT INTO `entity_set` VALUES(82, 5);
INSERT INTO `entity_set` VALUES(83, 5);
INSERT INTO `entity_set` VALUES(84, 5);
INSERT INTO `entity_set` VALUES(85, 5);
INSERT INTO `entity_set` VALUES(86, 5);
INSERT INTO `entity_set` VALUES(87, 5);
INSERT INTO `entity_set` VALUES(88, 5);
INSERT INTO `entity_set` VALUES(89, 5);
INSERT INTO `entity_set` VALUES(90, 5);
INSERT INTO `entity_set` VALUES(91, 6);
INSERT INTO `entity_set` VALUES(92, 6);
INSERT INTO `entity_set` VALUES(93, 6);
INSERT INTO `entity_set` VALUES(94, 6);
INSERT INTO `entity_set` VALUES(95, 6);
INSERT INTO `entity_set` VALUES(96, 6);
INSERT INTO `entity_set` VALUES(97, 6);
INSERT INTO `entity_set` VALUES(98, 6);
INSERT INTO `entity_set` VALUES(99, 6);
INSERT INTO `entity_set` VALUES(100, 6);
INSERT INTO `entity_set` VALUES(101, 6);
INSERT INTO `entity_set` VALUES(102, 6);
INSERT INTO `entity_set` VALUES(103, 6);
INSERT INTO `entity_set` VALUES(104, 6);
INSERT INTO `entity_set` VALUES(105, 6);
INSERT INTO `entity_set` VALUES(106, 6);
INSERT INTO `entity_set` VALUES(107, 6);
INSERT INTO `entity_set` VALUES(108, 6);
INSERT INTO `entity_set` VALUES(109, 6);
INSERT INTO `entity_set` VALUES(110, 6);
INSERT INTO `entity_set` VALUES(111, 6);
INSERT INTO `entity_set` VALUES(112, 6);
INSERT INTO `entity_set` VALUES(113, 6);
INSERT INTO `entity_set` VALUES(114, 6);
INSERT INTO `entity_set` VALUES(115, 6);
INSERT INTO `entity_set` VALUES(116, 6);
INSERT INTO `entity_set` VALUES(117, 6);
INSERT INTO `entity_set` VALUES(118, 6);
INSERT INTO `entity_set` VALUES(119, 6);
INSERT INTO `entity_set` VALUES(120, 6);
INSERT INTO `entity_set` VALUES(121, 6);
INSERT INTO `entity_set` VALUES(122, 6);
INSERT INTO `entity_set` VALUES(123, 6);
INSERT INTO `entity_set` VALUES(124, 6);
INSERT INTO `entity_set` VALUES(125, 6);
INSERT INTO `entity_set` VALUES(126, 6);
INSERT INTO `entity_set` VALUES(127, 6);
INSERT INTO `entity_set` VALUES(128, 6);
INSERT INTO `entity_set` VALUES(129, 6);
INSERT INTO `entity_set` VALUES(130, 6);
INSERT INTO `entity_set` VALUES(131, 7);
INSERT INTO `entity_set` VALUES(132, 7);
INSERT INTO `entity_set` VALUES(133, 7);
INSERT INTO `entity_set` VALUES(134, 7);
INSERT INTO `entity_set` VALUES(135, 7);
INSERT INTO `entity_set` VALUES(136, 7);
INSERT INTO `entity_set` VALUES(137, 7);
INSERT INTO `entity_set` VALUES(138, 7);
INSERT INTO `entity_set` VALUES(139, 7);
INSERT INTO `entity_set` VALUES(140, 7);
INSERT INTO `entity_set` VALUES(141, 7);
INSERT INTO `entity_set` VALUES(142, 7);
INSERT INTO `entity_set` VALUES(143, 7);
INSERT INTO `entity_set` VALUES(144, 7);
INSERT INTO `entity_set` VALUES(145, 7);
INSERT INTO `entity_set` VALUES(146, 7);
INSERT INTO `entity_set` VALUES(147, 7);
INSERT INTO `entity_set` VALUES(148, 7);
INSERT INTO `entity_set` VALUES(149, 7);
INSERT INTO `entity_set` VALUES(150, 7);
INSERT INTO `entity_set` VALUES(151, 7);
INSERT INTO `entity_set` VALUES(152, 7);
INSERT INTO `entity_set` VALUES(153, 7);
INSERT INTO `entity_set` VALUES(154, 7);
INSERT INTO `entity_set` VALUES(155, 8);
INSERT INTO `entity_set` VALUES(156, 8);
INSERT INTO `entity_set` VALUES(157, 8);
INSERT INTO `entity_set` VALUES(158, 8);
INSERT INTO `entity_set` VALUES(159, 8);
INSERT INTO `entity_set` VALUES(160, 8);
INSERT INTO `entity_set` VALUES(161, 8);
INSERT INTO `entity_set` VALUES(162, 8);
INSERT INTO `entity_set` VALUES(163, 8);
INSERT INTO `entity_set` VALUES(164, 8);
INSERT INTO `entity_set` VALUES(165, 8);
INSERT INTO `entity_set` VALUES(166, 8);
INSERT INTO `entity_set` VALUES(167, 8);
INSERT INTO `entity_set` VALUES(168, 8);
INSERT INTO `entity_set` VALUES(169, 8);
INSERT INTO `entity_set` VALUES(170, 8);
INSERT INTO `entity_set` VALUES(171, 8);
INSERT INTO `entity_set` VALUES(172, 8);
INSERT INTO `entity_set` VALUES(173, 8);
INSERT INTO `entity_set` VALUES(174, 8);
INSERT INTO `entity_set` VALUES(175, 8);
INSERT INTO `entity_set` VALUES(176, 8);
INSERT INTO `entity_set` VALUES(177, 8);
INSERT INTO `entity_set` VALUES(178, 8);
INSERT INTO `entity_set` VALUES(179, 8);
INSERT INTO `entity_set` VALUES(180, 8);
INSERT INTO `entity_set` VALUES(181, 8);
INSERT INTO `entity_set` VALUES(182, 8);
